package com.ruicai.teaching.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EduAttendanceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    public EduAttendanceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNull() {
            addCriterion("student_id is null");
            return (Criteria) this;
        }

        public Criteria andStudentIdIsNotNull() {
            addCriterion("student_id is not null");
            return (Criteria) this;
        }

        public Criteria andStudentIdEqualTo(String value) {
            addCriterion("student_id =", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotEqualTo(String value) {
            addCriterion("student_id <>", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThan(String value) {
            addCriterion("student_id >", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdGreaterThanOrEqualTo(String value) {
            addCriterion("student_id >=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThan(String value) {
            addCriterion("student_id <", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLessThanOrEqualTo(String value) {
            addCriterion("student_id <=", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdLike(String value) {
            addCriterion("student_id like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotLike(String value) {
            addCriterion("student_id not like", value, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdIn(List<String> values) {
            addCriterion("student_id in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotIn(List<String> values) {
            addCriterion("student_id not in", values, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdBetween(String value1, String value2) {
            addCriterion("student_id between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andStudentIdNotBetween(String value1, String value2) {
            addCriterion("student_id not between", value1, value2, "studentId");
            return (Criteria) this;
        }

        public Criteria andAttStatusIsNull() {
            addCriterion("att_status is null");
            return (Criteria) this;
        }

        public Criteria andAttStatusIsNotNull() {
            addCriterion("att_status is not null");
            return (Criteria) this;
        }

        public Criteria andAttStatusEqualTo(String value) {
            addCriterion("att_status =", value, "attStatus");
            return (Criteria) this;
        }

        public Criteria andAttStatusNotEqualTo(String value) {
            addCriterion("att_status <>", value, "attStatus");
            return (Criteria) this;
        }

        public Criteria andAttStatusGreaterThan(String value) {
            addCriterion("att_status >", value, "attStatus");
            return (Criteria) this;
        }

        public Criteria andAttStatusGreaterThanOrEqualTo(String value) {
            addCriterion("att_status >=", value, "attStatus");
            return (Criteria) this;
        }

        public Criteria andAttStatusLessThan(String value) {
            addCriterion("att_status <", value, "attStatus");
            return (Criteria) this;
        }

        public Criteria andAttStatusLessThanOrEqualTo(String value) {
            addCriterion("att_status <=", value, "attStatus");
            return (Criteria) this;
        }

        public Criteria andAttStatusLike(String value) {
            addCriterion("att_status like", value, "attStatus");
            return (Criteria) this;
        }

        public Criteria andAttStatusNotLike(String value) {
            addCriterion("att_status not like", value, "attStatus");
            return (Criteria) this;
        }

        public Criteria andAttStatusIn(List<String> values) {
            addCriterion("att_status in", values, "attStatus");
            return (Criteria) this;
        }

        public Criteria andAttStatusNotIn(List<String> values) {
            addCriterion("att_status not in", values, "attStatus");
            return (Criteria) this;
        }

        public Criteria andAttStatusBetween(String value1, String value2) {
            addCriterion("att_status between", value1, value2, "attStatus");
            return (Criteria) this;
        }

        public Criteria andAttStatusNotBetween(String value1, String value2) {
            addCriterion("att_status not between", value1, value2, "attStatus");
            return (Criteria) this;
        }

        public Criteria andAttTimeIsNull() {
            addCriterion("att_time is null");
            return (Criteria) this;
        }

        public Criteria andAttTimeIsNotNull() {
            addCriterion("att_time is not null");
            return (Criteria) this;
        }

        public Criteria andAttTimeEqualTo(Date value) {
            addCriterion("att_time =", value, "attTime");
            return (Criteria) this;
        }

        public Criteria andAttTimeNotEqualTo(Date value) {
            addCriterion("att_time <>", value, "attTime");
            return (Criteria) this;
        }

        public Criteria andAttTimeGreaterThan(Date value) {
            addCriterion("att_time >", value, "attTime");
            return (Criteria) this;
        }

        public Criteria andAttTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("att_time >=", value, "attTime");
            return (Criteria) this;
        }

        public Criteria andAttTimeLessThan(Date value) {
            addCriterion("att_time <", value, "attTime");
            return (Criteria) this;
        }

        public Criteria andAttTimeLessThanOrEqualTo(Date value) {
            addCriterion("att_time <=", value, "attTime");
            return (Criteria) this;
        }

        public Criteria andAttTimeIn(List<Date> values) {
            addCriterion("att_time in", values, "attTime");
            return (Criteria) this;
        }

        public Criteria andAttTimeNotIn(List<Date> values) {
            addCriterion("att_time not in", values, "attTime");
            return (Criteria) this;
        }

        public Criteria andAttTimeBetween(Date value1, Date value2) {
            addCriterion("att_time between", value1, value2, "attTime");
            return (Criteria) this;
        }

        public Criteria andAttTimeNotBetween(Date value1, Date value2) {
            addCriterion("att_time not between", value1, value2, "attTime");
            return (Criteria) this;
        }

        public Criteria andAttRemarkIsNull() {
            addCriterion("att_remark is null");
            return (Criteria) this;
        }

        public Criteria andAttRemarkIsNotNull() {
            addCriterion("att_remark is not null");
            return (Criteria) this;
        }

        public Criteria andAttRemarkEqualTo(String value) {
            addCriterion("att_remark =", value, "attRemark");
            return (Criteria) this;
        }

        public Criteria andAttRemarkNotEqualTo(String value) {
            addCriterion("att_remark <>", value, "attRemark");
            return (Criteria) this;
        }

        public Criteria andAttRemarkGreaterThan(String value) {
            addCriterion("att_remark >", value, "attRemark");
            return (Criteria) this;
        }

        public Criteria andAttRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("att_remark >=", value, "attRemark");
            return (Criteria) this;
        }

        public Criteria andAttRemarkLessThan(String value) {
            addCriterion("att_remark <", value, "attRemark");
            return (Criteria) this;
        }

        public Criteria andAttRemarkLessThanOrEqualTo(String value) {
            addCriterion("att_remark <=", value, "attRemark");
            return (Criteria) this;
        }

        public Criteria andAttRemarkLike(String value) {
            addCriterion("att_remark like", value, "attRemark");
            return (Criteria) this;
        }

        public Criteria andAttRemarkNotLike(String value) {
            addCriterion("att_remark not like", value, "attRemark");
            return (Criteria) this;
        }

        public Criteria andAttRemarkIn(List<String> values) {
            addCriterion("att_remark in", values, "attRemark");
            return (Criteria) this;
        }

        public Criteria andAttRemarkNotIn(List<String> values) {
            addCriterion("att_remark not in", values, "attRemark");
            return (Criteria) this;
        }

        public Criteria andAttRemarkBetween(String value1, String value2) {
            addCriterion("att_remark between", value1, value2, "attRemark");
            return (Criteria) this;
        }

        public Criteria andAttRemarkNotBetween(String value1, String value2) {
            addCriterion("att_remark not between", value1, value2, "attRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table edu_attendance
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}