package com.ruicai.teaching.entity;

import java.util.Date;

public class EduClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_class.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_class.head_teacher_id
     *
     * @mbggenerated
     */
    private String headTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_class.main_teacher_id
     *
     * @mbggenerated
     */
    private String mainTeacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_class.assistant_id
     *
     * @mbggenerated
     */
    private String assistantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_class.class_type
     *
     * @mbggenerated
     */
    private String classType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_class.class_name
     *
     * @mbggenerated
     */
    private String className;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_class.class_start_date
     *
     * @mbggenerated
     */
    private Date classStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_class.class_end_date
     *
     * @mbggenerated
     */
    private Date classEndDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_class.id
     *
     * @return the value of edu_class.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_class.id
     *
     * @param id the value for edu_class.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_class.head_teacher_id
     *
     * @return the value of edu_class.head_teacher_id
     *
     * @mbggenerated
     */
    public String getHeadTeacherId() {
        return headTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_class.head_teacher_id
     *
     * @param headTeacherId the value for edu_class.head_teacher_id
     *
     * @mbggenerated
     */
    public void setHeadTeacherId(String headTeacherId) {
        this.headTeacherId = headTeacherId == null ? null : headTeacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_class.main_teacher_id
     *
     * @return the value of edu_class.main_teacher_id
     *
     * @mbggenerated
     */
    public String getMainTeacherId() {
        return mainTeacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_class.main_teacher_id
     *
     * @param mainTeacherId the value for edu_class.main_teacher_id
     *
     * @mbggenerated
     */
    public void setMainTeacherId(String mainTeacherId) {
        this.mainTeacherId = mainTeacherId == null ? null : mainTeacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_class.assistant_id
     *
     * @return the value of edu_class.assistant_id
     *
     * @mbggenerated
     */
    public String getAssistantId() {
        return assistantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_class.assistant_id
     *
     * @param assistantId the value for edu_class.assistant_id
     *
     * @mbggenerated
     */
    public void setAssistantId(String assistantId) {
        this.assistantId = assistantId == null ? null : assistantId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_class.class_type
     *
     * @return the value of edu_class.class_type
     *
     * @mbggenerated
     */
    public String getClassType() {
        return classType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_class.class_type
     *
     * @param classType the value for edu_class.class_type
     *
     * @mbggenerated
     */
    public void setClassType(String classType) {
        this.classType = classType == null ? null : classType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_class.class_name
     *
     * @return the value of edu_class.class_name
     *
     * @mbggenerated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_class.class_name
     *
     * @param className the value for edu_class.class_name
     *
     * @mbggenerated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_class.class_start_date
     *
     * @return the value of edu_class.class_start_date
     *
     * @mbggenerated
     */
    public Date getClassStartDate() {
        return classStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_class.class_start_date
     *
     * @param classStartDate the value for edu_class.class_start_date
     *
     * @mbggenerated
     */
    public void setClassStartDate(Date classStartDate) {
        this.classStartDate = classStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_class.class_end_date
     *
     * @return the value of edu_class.class_end_date
     *
     * @mbggenerated
     */
    public Date getClassEndDate() {
        return classEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_class.class_end_date
     *
     * @param classEndDate the value for edu_class.class_end_date
     *
     * @mbggenerated
     */
    public void setClassEndDate(Date classEndDate) {
        this.classEndDate = classEndDate;
    }
}