package com.ruicai.teaching.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class EduStudentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table edu_student
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table edu_student
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table edu_student
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_student
     *
     * @mbggenerated
     */
    public EduStudentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_student
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_student
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_student
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_student
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_student
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_student
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_student
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_student
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_student
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_student
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table edu_student
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNull() {
            addCriterion("class_id is null");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNotNull() {
            addCriterion("class_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassIdEqualTo(String value) {
            addCriterion("class_id =", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotEqualTo(String value) {
            addCriterion("class_id <>", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThan(String value) {
            addCriterion("class_id >", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThanOrEqualTo(String value) {
            addCriterion("class_id >=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThan(String value) {
            addCriterion("class_id <", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThanOrEqualTo(String value) {
            addCriterion("class_id <=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLike(String value) {
            addCriterion("class_id like", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotLike(String value) {
            addCriterion("class_id not like", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdIn(List<String> values) {
            addCriterion("class_id in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotIn(List<String> values) {
            addCriterion("class_id not in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdBetween(String value1, String value2) {
            addCriterion("class_id between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotBetween(String value1, String value2) {
            addCriterion("class_id not between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andStuEducationIsNull() {
            addCriterion("stu_education is null");
            return (Criteria) this;
        }

        public Criteria andStuEducationIsNotNull() {
            addCriterion("stu_education is not null");
            return (Criteria) this;
        }

        public Criteria andStuEducationEqualTo(String value) {
            addCriterion("stu_education =", value, "stuEducation");
            return (Criteria) this;
        }

        public Criteria andStuEducationNotEqualTo(String value) {
            addCriterion("stu_education <>", value, "stuEducation");
            return (Criteria) this;
        }

        public Criteria andStuEducationGreaterThan(String value) {
            addCriterion("stu_education >", value, "stuEducation");
            return (Criteria) this;
        }

        public Criteria andStuEducationGreaterThanOrEqualTo(String value) {
            addCriterion("stu_education >=", value, "stuEducation");
            return (Criteria) this;
        }

        public Criteria andStuEducationLessThan(String value) {
            addCriterion("stu_education <", value, "stuEducation");
            return (Criteria) this;
        }

        public Criteria andStuEducationLessThanOrEqualTo(String value) {
            addCriterion("stu_education <=", value, "stuEducation");
            return (Criteria) this;
        }

        public Criteria andStuEducationLike(String value) {
            addCriterion("stu_education like", value, "stuEducation");
            return (Criteria) this;
        }

        public Criteria andStuEducationNotLike(String value) {
            addCriterion("stu_education not like", value, "stuEducation");
            return (Criteria) this;
        }

        public Criteria andStuEducationIn(List<String> values) {
            addCriterion("stu_education in", values, "stuEducation");
            return (Criteria) this;
        }

        public Criteria andStuEducationNotIn(List<String> values) {
            addCriterion("stu_education not in", values, "stuEducation");
            return (Criteria) this;
        }

        public Criteria andStuEducationBetween(String value1, String value2) {
            addCriterion("stu_education between", value1, value2, "stuEducation");
            return (Criteria) this;
        }

        public Criteria andStuEducationNotBetween(String value1, String value2) {
            addCriterion("stu_education not between", value1, value2, "stuEducation");
            return (Criteria) this;
        }

        public Criteria andStuSexIsNull() {
            addCriterion("stu_sex is null");
            return (Criteria) this;
        }

        public Criteria andStuSexIsNotNull() {
            addCriterion("stu_sex is not null");
            return (Criteria) this;
        }

        public Criteria andStuSexEqualTo(String value) {
            addCriterion("stu_sex =", value, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexNotEqualTo(String value) {
            addCriterion("stu_sex <>", value, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexGreaterThan(String value) {
            addCriterion("stu_sex >", value, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexGreaterThanOrEqualTo(String value) {
            addCriterion("stu_sex >=", value, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexLessThan(String value) {
            addCriterion("stu_sex <", value, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexLessThanOrEqualTo(String value) {
            addCriterion("stu_sex <=", value, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexLike(String value) {
            addCriterion("stu_sex like", value, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexNotLike(String value) {
            addCriterion("stu_sex not like", value, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexIn(List<String> values) {
            addCriterion("stu_sex in", values, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexNotIn(List<String> values) {
            addCriterion("stu_sex not in", values, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexBetween(String value1, String value2) {
            addCriterion("stu_sex between", value1, value2, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuSexNotBetween(String value1, String value2) {
            addCriterion("stu_sex not between", value1, value2, "stuSex");
            return (Criteria) this;
        }

        public Criteria andStuNameIsNull() {
            addCriterion("stu_name is null");
            return (Criteria) this;
        }

        public Criteria andStuNameIsNotNull() {
            addCriterion("stu_name is not null");
            return (Criteria) this;
        }

        public Criteria andStuNameEqualTo(String value) {
            addCriterion("stu_name =", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotEqualTo(String value) {
            addCriterion("stu_name <>", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameGreaterThan(String value) {
            addCriterion("stu_name >", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameGreaterThanOrEqualTo(String value) {
            addCriterion("stu_name >=", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameLessThan(String value) {
            addCriterion("stu_name <", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameLessThanOrEqualTo(String value) {
            addCriterion("stu_name <=", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameLike(String value) {
            addCriterion("stu_name like", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotLike(String value) {
            addCriterion("stu_name not like", value, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameIn(List<String> values) {
            addCriterion("stu_name in", values, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotIn(List<String> values) {
            addCriterion("stu_name not in", values, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameBetween(String value1, String value2) {
            addCriterion("stu_name between", value1, value2, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuNameNotBetween(String value1, String value2) {
            addCriterion("stu_name not between", value1, value2, "stuName");
            return (Criteria) this;
        }

        public Criteria andStuIdNumberIsNull() {
            addCriterion("stu_id_number is null");
            return (Criteria) this;
        }

        public Criteria andStuIdNumberIsNotNull() {
            addCriterion("stu_id_number is not null");
            return (Criteria) this;
        }

        public Criteria andStuIdNumberEqualTo(String value) {
            addCriterion("stu_id_number =", value, "stuIdNumber");
            return (Criteria) this;
        }

        public Criteria andStuIdNumberNotEqualTo(String value) {
            addCriterion("stu_id_number <>", value, "stuIdNumber");
            return (Criteria) this;
        }

        public Criteria andStuIdNumberGreaterThan(String value) {
            addCriterion("stu_id_number >", value, "stuIdNumber");
            return (Criteria) this;
        }

        public Criteria andStuIdNumberGreaterThanOrEqualTo(String value) {
            addCriterion("stu_id_number >=", value, "stuIdNumber");
            return (Criteria) this;
        }

        public Criteria andStuIdNumberLessThan(String value) {
            addCriterion("stu_id_number <", value, "stuIdNumber");
            return (Criteria) this;
        }

        public Criteria andStuIdNumberLessThanOrEqualTo(String value) {
            addCriterion("stu_id_number <=", value, "stuIdNumber");
            return (Criteria) this;
        }

        public Criteria andStuIdNumberLike(String value) {
            addCriterion("stu_id_number like", value, "stuIdNumber");
            return (Criteria) this;
        }

        public Criteria andStuIdNumberNotLike(String value) {
            addCriterion("stu_id_number not like", value, "stuIdNumber");
            return (Criteria) this;
        }

        public Criteria andStuIdNumberIn(List<String> values) {
            addCriterion("stu_id_number in", values, "stuIdNumber");
            return (Criteria) this;
        }

        public Criteria andStuIdNumberNotIn(List<String> values) {
            addCriterion("stu_id_number not in", values, "stuIdNumber");
            return (Criteria) this;
        }

        public Criteria andStuIdNumberBetween(String value1, String value2) {
            addCriterion("stu_id_number between", value1, value2, "stuIdNumber");
            return (Criteria) this;
        }

        public Criteria andStuIdNumberNotBetween(String value1, String value2) {
            addCriterion("stu_id_number not between", value1, value2, "stuIdNumber");
            return (Criteria) this;
        }

        public Criteria andStuSchoolIsNull() {
            addCriterion("stu_school is null");
            return (Criteria) this;
        }

        public Criteria andStuSchoolIsNotNull() {
            addCriterion("stu_school is not null");
            return (Criteria) this;
        }

        public Criteria andStuSchoolEqualTo(String value) {
            addCriterion("stu_school =", value, "stuSchool");
            return (Criteria) this;
        }

        public Criteria andStuSchoolNotEqualTo(String value) {
            addCriterion("stu_school <>", value, "stuSchool");
            return (Criteria) this;
        }

        public Criteria andStuSchoolGreaterThan(String value) {
            addCriterion("stu_school >", value, "stuSchool");
            return (Criteria) this;
        }

        public Criteria andStuSchoolGreaterThanOrEqualTo(String value) {
            addCriterion("stu_school >=", value, "stuSchool");
            return (Criteria) this;
        }

        public Criteria andStuSchoolLessThan(String value) {
            addCriterion("stu_school <", value, "stuSchool");
            return (Criteria) this;
        }

        public Criteria andStuSchoolLessThanOrEqualTo(String value) {
            addCriterion("stu_school <=", value, "stuSchool");
            return (Criteria) this;
        }

        public Criteria andStuSchoolLike(String value) {
            addCriterion("stu_school like", value, "stuSchool");
            return (Criteria) this;
        }

        public Criteria andStuSchoolNotLike(String value) {
            addCriterion("stu_school not like", value, "stuSchool");
            return (Criteria) this;
        }

        public Criteria andStuSchoolIn(List<String> values) {
            addCriterion("stu_school in", values, "stuSchool");
            return (Criteria) this;
        }

        public Criteria andStuSchoolNotIn(List<String> values) {
            addCriterion("stu_school not in", values, "stuSchool");
            return (Criteria) this;
        }

        public Criteria andStuSchoolBetween(String value1, String value2) {
            addCriterion("stu_school between", value1, value2, "stuSchool");
            return (Criteria) this;
        }

        public Criteria andStuSchoolNotBetween(String value1, String value2) {
            addCriterion("stu_school not between", value1, value2, "stuSchool");
            return (Criteria) this;
        }

        public Criteria andStuSpecialtyIsNull() {
            addCriterion("stu_specialty is null");
            return (Criteria) this;
        }

        public Criteria andStuSpecialtyIsNotNull() {
            addCriterion("stu_specialty is not null");
            return (Criteria) this;
        }

        public Criteria andStuSpecialtyEqualTo(String value) {
            addCriterion("stu_specialty =", value, "stuSpecialty");
            return (Criteria) this;
        }

        public Criteria andStuSpecialtyNotEqualTo(String value) {
            addCriterion("stu_specialty <>", value, "stuSpecialty");
            return (Criteria) this;
        }

        public Criteria andStuSpecialtyGreaterThan(String value) {
            addCriterion("stu_specialty >", value, "stuSpecialty");
            return (Criteria) this;
        }

        public Criteria andStuSpecialtyGreaterThanOrEqualTo(String value) {
            addCriterion("stu_specialty >=", value, "stuSpecialty");
            return (Criteria) this;
        }

        public Criteria andStuSpecialtyLessThan(String value) {
            addCriterion("stu_specialty <", value, "stuSpecialty");
            return (Criteria) this;
        }

        public Criteria andStuSpecialtyLessThanOrEqualTo(String value) {
            addCriterion("stu_specialty <=", value, "stuSpecialty");
            return (Criteria) this;
        }

        public Criteria andStuSpecialtyLike(String value) {
            addCriterion("stu_specialty like", value, "stuSpecialty");
            return (Criteria) this;
        }

        public Criteria andStuSpecialtyNotLike(String value) {
            addCriterion("stu_specialty not like", value, "stuSpecialty");
            return (Criteria) this;
        }

        public Criteria andStuSpecialtyIn(List<String> values) {
            addCriterion("stu_specialty in", values, "stuSpecialty");
            return (Criteria) this;
        }

        public Criteria andStuSpecialtyNotIn(List<String> values) {
            addCriterion("stu_specialty not in", values, "stuSpecialty");
            return (Criteria) this;
        }

        public Criteria andStuSpecialtyBetween(String value1, String value2) {
            addCriterion("stu_specialty between", value1, value2, "stuSpecialty");
            return (Criteria) this;
        }

        public Criteria andStuSpecialtyNotBetween(String value1, String value2) {
            addCriterion("stu_specialty not between", value1, value2, "stuSpecialty");
            return (Criteria) this;
        }

        public Criteria andStuGraduationIsNull() {
            addCriterion("stu_graduation is null");
            return (Criteria) this;
        }

        public Criteria andStuGraduationIsNotNull() {
            addCriterion("stu_graduation is not null");
            return (Criteria) this;
        }

        public Criteria andStuGraduationEqualTo(Date value) {
            addCriterionForJDBCDate("stu_graduation =", value, "stuGraduation");
            return (Criteria) this;
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        public Criteria andStuGraduationNotEqualTo(Date value) {
            addCriterionForJDBCDate("stu_graduation <>", value, "stuGraduation");
            return (Criteria) this;
        }

        public Criteria andStuGraduationGreaterThan(Date value) {
            addCriterionForJDBCDate("stu_graduation >", value, "stuGraduation");
            return (Criteria) this;
        }

        public Criteria andStuGraduationGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("stu_graduation >=", value, "stuGraduation");
            return (Criteria) this;
        }

        public Criteria andStuGraduationLessThan(Date value) {
            addCriterionForJDBCDate("stu_graduation <", value, "stuGraduation");
            return (Criteria) this;
        }

        public Criteria andStuGraduationLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("stu_graduation <=", value, "stuGraduation");
            return (Criteria) this;
        }

        public Criteria andStuGraduationIn(List<Date> values) {
            addCriterionForJDBCDate("stu_graduation in", values, "stuGraduation");
            return (Criteria) this;
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        public Criteria andStuGraduationNotIn(List<Date> values) {
            addCriterionForJDBCDate("stu_graduation not in", values, "stuGraduation");
            return (Criteria) this;
        }

        public Criteria andStuGraduationBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("stu_graduation between", value1, value2, "stuGraduation");
            return (Criteria) this;
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andStuGraduationNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("stu_graduation not between", value1, value2, "stuGraduation");
            return (Criteria) this;
        }

        public Criteria andStuPhoneIsNull() {
            addCriterion("stu_phone is null");
            return (Criteria) this;
        }

        public Criteria andStuPhoneIsNotNull() {
            addCriterion("stu_phone is not null");
            return (Criteria) this;
        }

        public Criteria andStuPhoneEqualTo(String value) {
            addCriterion("stu_phone =", value, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneNotEqualTo(String value) {
            addCriterion("stu_phone <>", value, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneGreaterThan(String value) {
            addCriterion("stu_phone >", value, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("stu_phone >=", value, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneLessThan(String value) {
            addCriterion("stu_phone <", value, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneLessThanOrEqualTo(String value) {
            addCriterion("stu_phone <=", value, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneLike(String value) {
            addCriterion("stu_phone like", value, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneNotLike(String value) {
            addCriterion("stu_phone not like", value, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneIn(List<String> values) {
            addCriterion("stu_phone in", values, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneNotIn(List<String> values) {
            addCriterion("stu_phone not in", values, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneBetween(String value1, String value2) {
            addCriterion("stu_phone between", value1, value2, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuPhoneNotBetween(String value1, String value2) {
            addCriterion("stu_phone not between", value1, value2, "stuPhone");
            return (Criteria) this;
        }

        public Criteria andStuFamilyPhoneIsNull() {
            addCriterion("stu_family_phone is null");
            return (Criteria) this;
        }

        public Criteria andStuFamilyPhoneIsNotNull() {
            addCriterion("stu_family_phone is not null");
            return (Criteria) this;
        }

        public Criteria andStuFamilyPhoneEqualTo(String value) {
            addCriterion("stu_family_phone =", value, "stuFamilyPhone");
            return (Criteria) this;
        }

        public Criteria andStuFamilyPhoneNotEqualTo(String value) {
            addCriterion("stu_family_phone <>", value, "stuFamilyPhone");
            return (Criteria) this;
        }

        public Criteria andStuFamilyPhoneGreaterThan(String value) {
            addCriterion("stu_family_phone >", value, "stuFamilyPhone");
            return (Criteria) this;
        }

        public Criteria andStuFamilyPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("stu_family_phone >=", value, "stuFamilyPhone");
            return (Criteria) this;
        }

        public Criteria andStuFamilyPhoneLessThan(String value) {
            addCriterion("stu_family_phone <", value, "stuFamilyPhone");
            return (Criteria) this;
        }

        public Criteria andStuFamilyPhoneLessThanOrEqualTo(String value) {
            addCriterion("stu_family_phone <=", value, "stuFamilyPhone");
            return (Criteria) this;
        }

        public Criteria andStuFamilyPhoneLike(String value) {
            addCriterion("stu_family_phone like", value, "stuFamilyPhone");
            return (Criteria) this;
        }

        public Criteria andStuFamilyPhoneNotLike(String value) {
            addCriterion("stu_family_phone not like", value, "stuFamilyPhone");
            return (Criteria) this;
        }

        public Criteria andStuFamilyPhoneIn(List<String> values) {
            addCriterion("stu_family_phone in", values, "stuFamilyPhone");
            return (Criteria) this;
        }

        public Criteria andStuFamilyPhoneNotIn(List<String> values) {
            addCriterion("stu_family_phone not in", values, "stuFamilyPhone");
            return (Criteria) this;
        }

        public Criteria andStuFamilyPhoneBetween(String value1, String value2) {
            addCriterion("stu_family_phone between", value1, value2, "stuFamilyPhone");
            return (Criteria) this;
        }

        public Criteria andStuFamilyPhoneNotBetween(String value1, String value2) {
            addCriterion("stu_family_phone not between", value1, value2, "stuFamilyPhone");
            return (Criteria) this;
        }

        public Criteria andStuPictureIsNull() {
            addCriterion("stu_picture is null");
            return (Criteria) this;
        }

        public Criteria andStuPictureIsNotNull() {
            addCriterion("stu_picture is not null");
            return (Criteria) this;
        }

        public Criteria andStuPictureEqualTo(String value) {
            addCriterion("stu_picture =", value, "stuPicture");
            return (Criteria) this;
        }

        public Criteria andStuPictureNotEqualTo(String value) {
            addCriterion("stu_picture <>", value, "stuPicture");
            return (Criteria) this;
        }

        public Criteria andStuPictureGreaterThan(String value) {
            addCriterion("stu_picture >", value, "stuPicture");
            return (Criteria) this;
        }

        public Criteria andStuPictureGreaterThanOrEqualTo(String value) {
            addCriterion("stu_picture >=", value, "stuPicture");
            return (Criteria) this;
        }

        public Criteria andStuPictureLessThan(String value) {
            addCriterion("stu_picture <", value, "stuPicture");
            return (Criteria) this;
        }

        public Criteria andStuPictureLessThanOrEqualTo(String value) {
            addCriterion("stu_picture <=", value, "stuPicture");
            return (Criteria) this;
        }

        public Criteria andStuPictureLike(String value) {
            addCriterion("stu_picture like", value, "stuPicture");
            return (Criteria) this;
        }

        public Criteria andStuPictureNotLike(String value) {
            addCriterion("stu_picture not like", value, "stuPicture");
            return (Criteria) this;
        }

        public Criteria andStuPictureIn(List<String> values) {
            addCriterion("stu_picture in", values, "stuPicture");
            return (Criteria) this;
        }

        public Criteria andStuPictureNotIn(List<String> values) {
            addCriterion("stu_picture not in", values, "stuPicture");
            return (Criteria) this;
        }

        public Criteria andStuPictureBetween(String value1, String value2) {
            addCriterion("stu_picture between", value1, value2, "stuPicture");
            return (Criteria) this;
        }

        public Criteria andStuPictureNotBetween(String value1, String value2) {
            addCriterion("stu_picture not between", value1, value2, "stuPicture");
            return (Criteria) this;
        }

        public Criteria andStuInsuranceIsNull() {
            addCriterion("stu_insurance is null");
            return (Criteria) this;
        }

        public Criteria andStuInsuranceIsNotNull() {
            addCriterion("stu_insurance is not null");
            return (Criteria) this;
        }

        public Criteria andStuInsuranceEqualTo(Short value) {
            addCriterion("stu_insurance =", value, "stuInsurance");
            return (Criteria) this;
        }

        public Criteria andStuInsuranceNotEqualTo(Short value) {
            addCriterion("stu_insurance <>", value, "stuInsurance");
            return (Criteria) this;
        }

        public Criteria andStuInsuranceGreaterThan(Short value) {
            addCriterion("stu_insurance >", value, "stuInsurance");
            return (Criteria) this;
        }

        public Criteria andStuInsuranceGreaterThanOrEqualTo(Short value) {
            addCriterion("stu_insurance >=", value, "stuInsurance");
            return (Criteria) this;
        }

        public Criteria andStuInsuranceLessThan(Short value) {
            addCriterion("stu_insurance <", value, "stuInsurance");
            return (Criteria) this;
        }

        public Criteria andStuInsuranceLessThanOrEqualTo(Short value) {
            addCriterion("stu_insurance <=", value, "stuInsurance");
            return (Criteria) this;
        }

        public Criteria andStuInsuranceIn(List<Short> values) {
            addCriterion("stu_insurance in", values, "stuInsurance");
            return (Criteria) this;
        }

        public Criteria andStuInsuranceNotIn(List<Short> values) {
            addCriterion("stu_insurance not in", values, "stuInsurance");
            return (Criteria) this;
        }

        public Criteria andStuInsuranceBetween(Short value1, Short value2) {
            addCriterion("stu_insurance between", value1, value2, "stuInsurance");
            return (Criteria) this;
        }

        public Criteria andStuInsuranceNotBetween(Short value1, Short value2) {
            addCriterion("stu_insurance not between", value1, value2, "stuInsurance");
            return (Criteria) this;
        }

        public Criteria andStuConductIsNull() {
            addCriterion("stu_conduct is null");
            return (Criteria) this;
        }

        public Criteria andStuConductIsNotNull() {
            addCriterion("stu_conduct is not null");
            return (Criteria) this;
        }

        public Criteria andStuConductEqualTo(Integer value) {
            addCriterion("stu_conduct =", value, "stuConduct");
            return (Criteria) this;
        }

        public Criteria andStuConductNotEqualTo(Integer value) {
            addCriterion("stu_conduct <>", value, "stuConduct");
            return (Criteria) this;
        }

        public Criteria andStuConductGreaterThan(Integer value) {
            addCriterion("stu_conduct >", value, "stuConduct");
            return (Criteria) this;
        }

        public Criteria andStuConductGreaterThanOrEqualTo(Integer value) {
            addCriterion("stu_conduct >=", value, "stuConduct");
            return (Criteria) this;
        }

        public Criteria andStuConductLessThan(Integer value) {
            addCriterion("stu_conduct <", value, "stuConduct");
            return (Criteria) this;
        }

        public Criteria andStuConductLessThanOrEqualTo(Integer value) {
            addCriterion("stu_conduct <=", value, "stuConduct");
            return (Criteria) this;
        }

        public Criteria andStuConductIn(List<Integer> values) {
            addCriterion("stu_conduct in", values, "stuConduct");
            return (Criteria) this;
        }

        public Criteria andStuConductNotIn(List<Integer> values) {
            addCriterion("stu_conduct not in", values, "stuConduct");
            return (Criteria) this;
        }

        public Criteria andStuConductBetween(Integer value1, Integer value2) {
            addCriterion("stu_conduct between", value1, value2, "stuConduct");
            return (Criteria) this;
        }

        public Criteria andStuConductNotBetween(Integer value1, Integer value2) {
            addCriterion("stu_conduct not between", value1, value2, "stuConduct");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table edu_student
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table edu_student
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}