package com.ruicai.teaching.entity;

import java.util.Date;

public class EduStudent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_student.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_student.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_student.class_id
     *
     * @mbggenerated
     */
    private String classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_student.stu_education
     *
     * @mbggenerated
     */
    private String stuEducation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_student.stu_sex
     *
     * @mbggenerated
     */
    private String stuSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_student.stu_name
     *
     * @mbggenerated
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_student.stu_id_number
     *
     * @mbggenerated
     */
    private String stuIdNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_student.stu_school
     *
     * @mbggenerated
     */
    private String stuSchool;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_student.stu_specialty
     *
     * @mbggenerated
     */
    private String stuSpecialty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_student.stu_graduation
     *
     * @mbggenerated
     */
    private Date stuGraduation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_student.stu_phone
     *
     * @mbggenerated
     */
    private String stuPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_student.stu_family_phone
     *
     * @mbggenerated
     */
    private String stuFamilyPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_student.stu_picture
     *
     * @mbggenerated
     */
    private String stuPicture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_student.stu_insurance
     *
     * @mbggenerated
     */
    private Short stuInsurance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_student.stu_conduct
     *
     * @mbggenerated
     */
    private Integer stuConduct;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_student.id
     *
     * @return the value of edu_student.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_student.id
     *
     * @param id the value for edu_student.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_student.user_id
     *
     * @return the value of edu_student.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_student.user_id
     *
     * @param userId the value for edu_student.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_student.class_id
     *
     * @return the value of edu_student.class_id
     *
     * @mbggenerated
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_student.class_id
     *
     * @param classId the value for edu_student.class_id
     *
     * @mbggenerated
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_student.stu_education
     *
     * @return the value of edu_student.stu_education
     *
     * @mbggenerated
     */
    public String getStuEducation() {
        return stuEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_student.stu_education
     *
     * @param stuEducation the value for edu_student.stu_education
     *
     * @mbggenerated
     */
    public void setStuEducation(String stuEducation) {
        this.stuEducation = stuEducation == null ? null : stuEducation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_student.stu_sex
     *
     * @return the value of edu_student.stu_sex
     *
     * @mbggenerated
     */
    public String getStuSex() {
        return stuSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_student.stu_sex
     *
     * @param stuSex the value for edu_student.stu_sex
     *
     * @mbggenerated
     */
    public void setStuSex(String stuSex) {
        this.stuSex = stuSex == null ? null : stuSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_student.stu_name
     *
     * @return the value of edu_student.stu_name
     *
     * @mbggenerated
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_student.stu_name
     *
     * @param stuName the value for edu_student.stu_name
     *
     * @mbggenerated
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_student.stu_id_number
     *
     * @return the value of edu_student.stu_id_number
     *
     * @mbggenerated
     */
    public String getStuIdNumber() {
        return stuIdNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_student.stu_id_number
     *
     * @param stuIdNumber the value for edu_student.stu_id_number
     *
     * @mbggenerated
     */
    public void setStuIdNumber(String stuIdNumber) {
        this.stuIdNumber = stuIdNumber == null ? null : stuIdNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_student.stu_school
     *
     * @return the value of edu_student.stu_school
     *
     * @mbggenerated
     */
    public String getStuSchool() {
        return stuSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_student.stu_school
     *
     * @param stuSchool the value for edu_student.stu_school
     *
     * @mbggenerated
     */
    public void setStuSchool(String stuSchool) {
        this.stuSchool = stuSchool == null ? null : stuSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_student.stu_specialty
     *
     * @return the value of edu_student.stu_specialty
     *
     * @mbggenerated
     */
    public String getStuSpecialty() {
        return stuSpecialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_student.stu_specialty
     *
     * @param stuSpecialty the value for edu_student.stu_specialty
     *
     * @mbggenerated
     */
    public void setStuSpecialty(String stuSpecialty) {
        this.stuSpecialty = stuSpecialty == null ? null : stuSpecialty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_student.stu_graduation
     *
     * @return the value of edu_student.stu_graduation
     *
     * @mbggenerated
     */
    public Date getStuGraduation() {
        return stuGraduation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_student.stu_graduation
     *
     * @param stuGraduation the value for edu_student.stu_graduation
     *
     * @mbggenerated
     */
    public void setStuGraduation(Date stuGraduation) {
        this.stuGraduation = stuGraduation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_student.stu_phone
     *
     * @return the value of edu_student.stu_phone
     *
     * @mbggenerated
     */
    public String getStuPhone() {
        return stuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_student.stu_phone
     *
     * @param stuPhone the value for edu_student.stu_phone
     *
     * @mbggenerated
     */
    public void setStuPhone(String stuPhone) {
        this.stuPhone = stuPhone == null ? null : stuPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_student.stu_family_phone
     *
     * @return the value of edu_student.stu_family_phone
     *
     * @mbggenerated
     */
    public String getStuFamilyPhone() {
        return stuFamilyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_student.stu_family_phone
     *
     * @param stuFamilyPhone the value for edu_student.stu_family_phone
     *
     * @mbggenerated
     */
    public void setStuFamilyPhone(String stuFamilyPhone) {
        this.stuFamilyPhone = stuFamilyPhone == null ? null : stuFamilyPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_student.stu_picture
     *
     * @return the value of edu_student.stu_picture
     *
     * @mbggenerated
     */
    public String getStuPicture() {
        return stuPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_student.stu_picture
     *
     * @param stuPicture the value for edu_student.stu_picture
     *
     * @mbggenerated
     */
    public void setStuPicture(String stuPicture) {
        this.stuPicture = stuPicture == null ? null : stuPicture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_student.stu_insurance
     *
     * @return the value of edu_student.stu_insurance
     *
     * @mbggenerated
     */
    public Short getStuInsurance() {
        return stuInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_student.stu_insurance
     *
     * @param stuInsurance the value for edu_student.stu_insurance
     *
     * @mbggenerated
     */
    public void setStuInsurance(Short stuInsurance) {
        this.stuInsurance = stuInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_student.stu_conduct
     *
     * @return the value of edu_student.stu_conduct
     *
     * @mbggenerated
     */
    public Integer getStuConduct() {
        return stuConduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_student.stu_conduct
     *
     * @param stuConduct the value for edu_student.stu_conduct
     *
     * @mbggenerated
     */
    public void setStuConduct(Integer stuConduct) {
        this.stuConduct = stuConduct;
    }
}