package com.ruicai.teaching.entity;

public class EduTeacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.teacher_type
     *
     * @mbggenerated
     */
    private String teacherType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.teacher_speciality
     *
     * @mbggenerated
     */
    private String teacherSpeciality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.teacher_sex
     *
     * @mbggenerated
     */
    private String teacherSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.teacher_name
     *
     * @mbggenerated
     */
    private String teacherName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.teacher_phone
     *
     * @mbggenerated
     */
    private String teacherPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.teacher_introduction
     *
     * @mbggenerated
     */
    private String teacherIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_teacher.teacher_picture
     *
     * @mbggenerated
     */
    private String teacherPicture;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.id
     *
     * @return the value of edu_teacher.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.id
     *
     * @param id the value for edu_teacher.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.user_id
     *
     * @return the value of edu_teacher.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.user_id
     *
     * @param userId the value for edu_teacher.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.teacher_type
     *
     * @return the value of edu_teacher.teacher_type
     *
     * @mbggenerated
     */
    public String getTeacherType() {
        return teacherType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.teacher_type
     *
     * @param teacherType the value for edu_teacher.teacher_type
     *
     * @mbggenerated
     */
    public void setTeacherType(String teacherType) {
        this.teacherType = teacherType == null ? null : teacherType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.teacher_speciality
     *
     * @return the value of edu_teacher.teacher_speciality
     *
     * @mbggenerated
     */
    public String getTeacherSpeciality() {
        return teacherSpeciality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.teacher_speciality
     *
     * @param teacherSpeciality the value for edu_teacher.teacher_speciality
     *
     * @mbggenerated
     */
    public void setTeacherSpeciality(String teacherSpeciality) {
        this.teacherSpeciality = teacherSpeciality == null ? null : teacherSpeciality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.teacher_sex
     *
     * @return the value of edu_teacher.teacher_sex
     *
     * @mbggenerated
     */
    public String getTeacherSex() {
        return teacherSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.teacher_sex
     *
     * @param teacherSex the value for edu_teacher.teacher_sex
     *
     * @mbggenerated
     */
    public void setTeacherSex(String teacherSex) {
        this.teacherSex = teacherSex == null ? null : teacherSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.teacher_name
     *
     * @return the value of edu_teacher.teacher_name
     *
     * @mbggenerated
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.teacher_name
     *
     * @param teacherName the value for edu_teacher.teacher_name
     *
     * @mbggenerated
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.teacher_phone
     *
     * @return the value of edu_teacher.teacher_phone
     *
     * @mbggenerated
     */
    public String getTeacherPhone() {
        return teacherPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.teacher_phone
     *
     * @param teacherPhone the value for edu_teacher.teacher_phone
     *
     * @mbggenerated
     */
    public void setTeacherPhone(String teacherPhone) {
        this.teacherPhone = teacherPhone == null ? null : teacherPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.teacher_introduction
     *
     * @return the value of edu_teacher.teacher_introduction
     *
     * @mbggenerated
     */
    public String getTeacherIntroduction() {
        return teacherIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.teacher_introduction
     *
     * @param teacherIntroduction the value for edu_teacher.teacher_introduction
     *
     * @mbggenerated
     */
    public void setTeacherIntroduction(String teacherIntroduction) {
        this.teacherIntroduction = teacherIntroduction == null ? null : teacherIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_teacher.teacher_picture
     *
     * @return the value of edu_teacher.teacher_picture
     *
     * @mbggenerated
     */
    public String getTeacherPicture() {
        return teacherPicture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_teacher.teacher_picture
     *
     * @param teacherPicture the value for edu_teacher.teacher_picture
     *
     * @mbggenerated
     */
    public void setTeacherPicture(String teacherPicture) {
        this.teacherPicture = teacherPicture == null ? null : teacherPicture.trim();
    }
}