package com.ruicai.teaching.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EduWorkExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    public EduWorkExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTeacherIdIsNull() {
            addCriterion("teacher_id is null");
            return (Criteria) this;
        }

        public Criteria andTeacherIdIsNotNull() {
            addCriterion("teacher_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherIdEqualTo(String value) {
            addCriterion("teacher_id =", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotEqualTo(String value) {
            addCriterion("teacher_id <>", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdGreaterThan(String value) {
            addCriterion("teacher_id >", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_id >=", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdLessThan(String value) {
            addCriterion("teacher_id <", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdLessThanOrEqualTo(String value) {
            addCriterion("teacher_id <=", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdLike(String value) {
            addCriterion("teacher_id like", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotLike(String value) {
            addCriterion("teacher_id not like", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdIn(List<String> values) {
            addCriterion("teacher_id in", values, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotIn(List<String> values) {
            addCriterion("teacher_id not in", values, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdBetween(String value1, String value2) {
            addCriterion("teacher_id between", value1, value2, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotBetween(String value1, String value2) {
            addCriterion("teacher_id not between", value1, value2, "teacherId");
            return (Criteria) this;
        }

        public Criteria andWorkTypeIsNull() {
            addCriterion("work_type is null");
            return (Criteria) this;
        }

        public Criteria andWorkTypeIsNotNull() {
            addCriterion("work_type is not null");
            return (Criteria) this;
        }

        public Criteria andWorkTypeEqualTo(String value) {
            addCriterion("work_type =", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotEqualTo(String value) {
            addCriterion("work_type <>", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeGreaterThan(String value) {
            addCriterion("work_type >", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeGreaterThanOrEqualTo(String value) {
            addCriterion("work_type >=", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeLessThan(String value) {
            addCriterion("work_type <", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeLessThanOrEqualTo(String value) {
            addCriterion("work_type <=", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeLike(String value) {
            addCriterion("work_type like", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotLike(String value) {
            addCriterion("work_type not like", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeIn(List<String> values) {
            addCriterion("work_type in", values, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotIn(List<String> values) {
            addCriterion("work_type not in", values, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeBetween(String value1, String value2) {
            addCriterion("work_type between", value1, value2, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotBetween(String value1, String value2) {
            addCriterion("work_type not between", value1, value2, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkUrlIsNull() {
            addCriterion("work_url is null");
            return (Criteria) this;
        }

        public Criteria andWorkUrlIsNotNull() {
            addCriterion("work_url is not null");
            return (Criteria) this;
        }

        public Criteria andWorkUrlEqualTo(String value) {
            addCriterion("work_url =", value, "workUrl");
            return (Criteria) this;
        }

        public Criteria andWorkUrlNotEqualTo(String value) {
            addCriterion("work_url <>", value, "workUrl");
            return (Criteria) this;
        }

        public Criteria andWorkUrlGreaterThan(String value) {
            addCriterion("work_url >", value, "workUrl");
            return (Criteria) this;
        }

        public Criteria andWorkUrlGreaterThanOrEqualTo(String value) {
            addCriterion("work_url >=", value, "workUrl");
            return (Criteria) this;
        }

        public Criteria andWorkUrlLessThan(String value) {
            addCriterion("work_url <", value, "workUrl");
            return (Criteria) this;
        }

        public Criteria andWorkUrlLessThanOrEqualTo(String value) {
            addCriterion("work_url <=", value, "workUrl");
            return (Criteria) this;
        }

        public Criteria andWorkUrlLike(String value) {
            addCriterion("work_url like", value, "workUrl");
            return (Criteria) this;
        }

        public Criteria andWorkUrlNotLike(String value) {
            addCriterion("work_url not like", value, "workUrl");
            return (Criteria) this;
        }

        public Criteria andWorkUrlIn(List<String> values) {
            addCriterion("work_url in", values, "workUrl");
            return (Criteria) this;
        }

        public Criteria andWorkUrlNotIn(List<String> values) {
            addCriterion("work_url not in", values, "workUrl");
            return (Criteria) this;
        }

        public Criteria andWorkUrlBetween(String value1, String value2) {
            addCriterion("work_url between", value1, value2, "workUrl");
            return (Criteria) this;
        }

        public Criteria andWorkUrlNotBetween(String value1, String value2) {
            addCriterion("work_url not between", value1, value2, "workUrl");
            return (Criteria) this;
        }

        public Criteria andWorkUploadTimeIsNull() {
            addCriterion("work_upload_time is null");
            return (Criteria) this;
        }

        public Criteria andWorkUploadTimeIsNotNull() {
            addCriterion("work_upload_time is not null");
            return (Criteria) this;
        }

        public Criteria andWorkUploadTimeEqualTo(Date value) {
            addCriterion("work_upload_time =", value, "workUploadTime");
            return (Criteria) this;
        }

        public Criteria andWorkUploadTimeNotEqualTo(Date value) {
            addCriterion("work_upload_time <>", value, "workUploadTime");
            return (Criteria) this;
        }

        public Criteria andWorkUploadTimeGreaterThan(Date value) {
            addCriterion("work_upload_time >", value, "workUploadTime");
            return (Criteria) this;
        }

        public Criteria andWorkUploadTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("work_upload_time >=", value, "workUploadTime");
            return (Criteria) this;
        }

        public Criteria andWorkUploadTimeLessThan(Date value) {
            addCriterion("work_upload_time <", value, "workUploadTime");
            return (Criteria) this;
        }

        public Criteria andWorkUploadTimeLessThanOrEqualTo(Date value) {
            addCriterion("work_upload_time <=", value, "workUploadTime");
            return (Criteria) this;
        }

        public Criteria andWorkUploadTimeIn(List<Date> values) {
            addCriterion("work_upload_time in", values, "workUploadTime");
            return (Criteria) this;
        }

        public Criteria andWorkUploadTimeNotIn(List<Date> values) {
            addCriterion("work_upload_time not in", values, "workUploadTime");
            return (Criteria) this;
        }

        public Criteria andWorkUploadTimeBetween(Date value1, Date value2) {
            addCriterion("work_upload_time between", value1, value2, "workUploadTime");
            return (Criteria) this;
        }

        public Criteria andWorkUploadTimeNotBetween(Date value1, Date value2) {
            addCriterion("work_upload_time not between", value1, value2, "workUploadTime");
            return (Criteria) this;
        }

        public Criteria andWorkRemarkIsNull() {
            addCriterion("work_remark is null");
            return (Criteria) this;
        }

        public Criteria andWorkRemarkIsNotNull() {
            addCriterion("work_remark is not null");
            return (Criteria) this;
        }

        public Criteria andWorkRemarkEqualTo(String value) {
            addCriterion("work_remark =", value, "workRemark");
            return (Criteria) this;
        }

        public Criteria andWorkRemarkNotEqualTo(String value) {
            addCriterion("work_remark <>", value, "workRemark");
            return (Criteria) this;
        }

        public Criteria andWorkRemarkGreaterThan(String value) {
            addCriterion("work_remark >", value, "workRemark");
            return (Criteria) this;
        }

        public Criteria andWorkRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("work_remark >=", value, "workRemark");
            return (Criteria) this;
        }

        public Criteria andWorkRemarkLessThan(String value) {
            addCriterion("work_remark <", value, "workRemark");
            return (Criteria) this;
        }

        public Criteria andWorkRemarkLessThanOrEqualTo(String value) {
            addCriterion("work_remark <=", value, "workRemark");
            return (Criteria) this;
        }

        public Criteria andWorkRemarkLike(String value) {
            addCriterion("work_remark like", value, "workRemark");
            return (Criteria) this;
        }

        public Criteria andWorkRemarkNotLike(String value) {
            addCriterion("work_remark not like", value, "workRemark");
            return (Criteria) this;
        }

        public Criteria andWorkRemarkIn(List<String> values) {
            addCriterion("work_remark in", values, "workRemark");
            return (Criteria) this;
        }

        public Criteria andWorkRemarkNotIn(List<String> values) {
            addCriterion("work_remark not in", values, "workRemark");
            return (Criteria) this;
        }

        public Criteria andWorkRemarkBetween(String value1, String value2) {
            addCriterion("work_remark between", value1, value2, "workRemark");
            return (Criteria) this;
        }

        public Criteria andWorkRemarkNotBetween(String value1, String value2) {
            addCriterion("work_remark not between", value1, value2, "workRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table edu_work
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}