package com.ruicai.teaching.entity;

import java.util.Date;

public class EduWork {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_work.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_work.teacher_id
     *
     * @mbggenerated
     */
    private String teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_work.work_type
     *
     * @mbggenerated
     */
    private String workType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_work.work_url
     *
     * @mbggenerated
     */
    private String workUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_work.work_upload_time
     *
     * @mbggenerated
     */
    private Date workUploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column edu_work.work_remark
     *
     * @mbggenerated
     */
    private String workRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_work.id
     *
     * @return the value of edu_work.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_work.id
     *
     * @param id the value for edu_work.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_work.teacher_id
     *
     * @return the value of edu_work.teacher_id
     *
     * @mbggenerated
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_work.teacher_id
     *
     * @param teacherId the value for edu_work.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_work.work_type
     *
     * @return the value of edu_work.work_type
     *
     * @mbggenerated
     */
    public String getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_work.work_type
     *
     * @param workType the value for edu_work.work_type
     *
     * @mbggenerated
     */
    public void setWorkType(String workType) {
        this.workType = workType == null ? null : workType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_work.work_url
     *
     * @return the value of edu_work.work_url
     *
     * @mbggenerated
     */
    public String getWorkUrl() {
        return workUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_work.work_url
     *
     * @param workUrl the value for edu_work.work_url
     *
     * @mbggenerated
     */
    public void setWorkUrl(String workUrl) {
        this.workUrl = workUrl == null ? null : workUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_work.work_upload_time
     *
     * @return the value of edu_work.work_upload_time
     *
     * @mbggenerated
     */
    public Date getWorkUploadTime() {
        return workUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_work.work_upload_time
     *
     * @param workUploadTime the value for edu_work.work_upload_time
     *
     * @mbggenerated
     */
    public void setWorkUploadTime(Date workUploadTime) {
        this.workUploadTime = workUploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column edu_work.work_remark
     *
     * @return the value of edu_work.work_remark
     *
     * @mbggenerated
     */
    public String getWorkRemark() {
        return workRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column edu_work.work_remark
     *
     * @param workRemark the value for edu_work.work_remark
     *
     * @mbggenerated
     */
    public void setWorkRemark(String workRemark) {
        this.workRemark = workRemark == null ? null : workRemark.trim();
    }
}