package com.ruicai.teaching.entity;

import java.util.Date;

public class EvaEvaluation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eva_evaluation.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eva_evaluation.student_id
     *
     * @mbggenerated
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eva_evaluation.teacher_id
     *
     * @mbggenerated
     */
    private String teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eva_evaluation.evaluation_time
     *
     * @mbggenerated
     */
    private Date evaluationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eva_evaluation.evaluation_feedback
     *
     * @mbggenerated
     */
    private String evaluationFeedback;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eva_evaluation.id
     *
     * @return the value of eva_evaluation.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eva_evaluation.id
     *
     * @param id the value for eva_evaluation.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eva_evaluation.student_id
     *
     * @return the value of eva_evaluation.student_id
     *
     * @mbggenerated
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eva_evaluation.student_id
     *
     * @param studentId the value for eva_evaluation.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eva_evaluation.teacher_id
     *
     * @return the value of eva_evaluation.teacher_id
     *
     * @mbggenerated
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eva_evaluation.teacher_id
     *
     * @param teacherId the value for eva_evaluation.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eva_evaluation.evaluation_time
     *
     * @return the value of eva_evaluation.evaluation_time
     *
     * @mbggenerated
     */
    public Date getEvaluationTime() {
        return evaluationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eva_evaluation.evaluation_time
     *
     * @param evaluationTime the value for eva_evaluation.evaluation_time
     *
     * @mbggenerated
     */
    public void setEvaluationTime(Date evaluationTime) {
        this.evaluationTime = evaluationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eva_evaluation.evaluation_feedback
     *
     * @return the value of eva_evaluation.evaluation_feedback
     *
     * @mbggenerated
     */
    public String getEvaluationFeedback() {
        return evaluationFeedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eva_evaluation.evaluation_feedback
     *
     * @param evaluationFeedback the value for eva_evaluation.evaluation_feedback
     *
     * @mbggenerated
     */
    public void setEvaluationFeedback(String evaluationFeedback) {
        this.evaluationFeedback = evaluationFeedback == null ? null : evaluationFeedback.trim();
    }
}