package com.ruicai.teaching.entity;

public class EvaEvaluationDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eva_evaluation_detail.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eva_evaluation_detail.evaluation_id
     *
     * @mbggenerated
     */
    private String evaluationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eva_evaluation_detail.item_id
     *
     * @mbggenerated
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eva_evaluation_detail.detail_score
     *
     * @mbggenerated
     */
    private Short detailScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eva_evaluation_detail.id
     *
     * @return the value of eva_evaluation_detail.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eva_evaluation_detail.id
     *
     * @param id the value for eva_evaluation_detail.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eva_evaluation_detail.evaluation_id
     *
     * @return the value of eva_evaluation_detail.evaluation_id
     *
     * @mbggenerated
     */
    public String getEvaluationId() {
        return evaluationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eva_evaluation_detail.evaluation_id
     *
     * @param evaluationId the value for eva_evaluation_detail.evaluation_id
     *
     * @mbggenerated
     */
    public void setEvaluationId(String evaluationId) {
        this.evaluationId = evaluationId == null ? null : evaluationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eva_evaluation_detail.item_id
     *
     * @return the value of eva_evaluation_detail.item_id
     *
     * @mbggenerated
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eva_evaluation_detail.item_id
     *
     * @param itemId the value for eva_evaluation_detail.item_id
     *
     * @mbggenerated
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eva_evaluation_detail.detail_score
     *
     * @return the value of eva_evaluation_detail.detail_score
     *
     * @mbggenerated
     */
    public Short getDetailScore() {
        return detailScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eva_evaluation_detail.detail_score
     *
     * @param detailScore the value for eva_evaluation_detail.detail_score
     *
     * @mbggenerated
     */
    public void setDetailScore(Short detailScore) {
        this.detailScore = detailScore;
    }
}