package com.ruicai.teaching.entity;

import java.util.ArrayList;
import java.util.List;

public class ExamPaperExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    public ExamPaperExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPaperStageIsNull() {
            addCriterion("paper_stage is null");
            return (Criteria) this;
        }

        public Criteria andPaperStageIsNotNull() {
            addCriterion("paper_stage is not null");
            return (Criteria) this;
        }

        public Criteria andPaperStageEqualTo(String value) {
            addCriterion("paper_stage =", value, "paperStage");
            return (Criteria) this;
        }

        public Criteria andPaperStageNotEqualTo(String value) {
            addCriterion("paper_stage <>", value, "paperStage");
            return (Criteria) this;
        }

        public Criteria andPaperStageGreaterThan(String value) {
            addCriterion("paper_stage >", value, "paperStage");
            return (Criteria) this;
        }

        public Criteria andPaperStageGreaterThanOrEqualTo(String value) {
            addCriterion("paper_stage >=", value, "paperStage");
            return (Criteria) this;
        }

        public Criteria andPaperStageLessThan(String value) {
            addCriterion("paper_stage <", value, "paperStage");
            return (Criteria) this;
        }

        public Criteria andPaperStageLessThanOrEqualTo(String value) {
            addCriterion("paper_stage <=", value, "paperStage");
            return (Criteria) this;
        }

        public Criteria andPaperStageLike(String value) {
            addCriterion("paper_stage like", value, "paperStage");
            return (Criteria) this;
        }

        public Criteria andPaperStageNotLike(String value) {
            addCriterion("paper_stage not like", value, "paperStage");
            return (Criteria) this;
        }

        public Criteria andPaperStageIn(List<String> values) {
            addCriterion("paper_stage in", values, "paperStage");
            return (Criteria) this;
        }

        public Criteria andPaperStageNotIn(List<String> values) {
            addCriterion("paper_stage not in", values, "paperStage");
            return (Criteria) this;
        }

        public Criteria andPaperStageBetween(String value1, String value2) {
            addCriterion("paper_stage between", value1, value2, "paperStage");
            return (Criteria) this;
        }

        public Criteria andPaperStageNotBetween(String value1, String value2) {
            addCriterion("paper_stage not between", value1, value2, "paperStage");
            return (Criteria) this;
        }

        public Criteria andPaperSubjectIsNull() {
            addCriterion("paper_subject is null");
            return (Criteria) this;
        }

        public Criteria andPaperSubjectIsNotNull() {
            addCriterion("paper_subject is not null");
            return (Criteria) this;
        }

        public Criteria andPaperSubjectEqualTo(String value) {
            addCriterion("paper_subject =", value, "paperSubject");
            return (Criteria) this;
        }

        public Criteria andPaperSubjectNotEqualTo(String value) {
            addCriterion("paper_subject <>", value, "paperSubject");
            return (Criteria) this;
        }

        public Criteria andPaperSubjectGreaterThan(String value) {
            addCriterion("paper_subject >", value, "paperSubject");
            return (Criteria) this;
        }

        public Criteria andPaperSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("paper_subject >=", value, "paperSubject");
            return (Criteria) this;
        }

        public Criteria andPaperSubjectLessThan(String value) {
            addCriterion("paper_subject <", value, "paperSubject");
            return (Criteria) this;
        }

        public Criteria andPaperSubjectLessThanOrEqualTo(String value) {
            addCriterion("paper_subject <=", value, "paperSubject");
            return (Criteria) this;
        }

        public Criteria andPaperSubjectLike(String value) {
            addCriterion("paper_subject like", value, "paperSubject");
            return (Criteria) this;
        }

        public Criteria andPaperSubjectNotLike(String value) {
            addCriterion("paper_subject not like", value, "paperSubject");
            return (Criteria) this;
        }

        public Criteria andPaperSubjectIn(List<String> values) {
            addCriterion("paper_subject in", values, "paperSubject");
            return (Criteria) this;
        }

        public Criteria andPaperSubjectNotIn(List<String> values) {
            addCriterion("paper_subject not in", values, "paperSubject");
            return (Criteria) this;
        }

        public Criteria andPaperSubjectBetween(String value1, String value2) {
            addCriterion("paper_subject between", value1, value2, "paperSubject");
            return (Criteria) this;
        }

        public Criteria andPaperSubjectNotBetween(String value1, String value2) {
            addCriterion("paper_subject not between", value1, value2, "paperSubject");
            return (Criteria) this;
        }

        public Criteria andPaperStatusIsNull() {
            addCriterion("paper_status is null");
            return (Criteria) this;
        }

        public Criteria andPaperStatusIsNotNull() {
            addCriterion("paper_status is not null");
            return (Criteria) this;
        }

        public Criteria andPaperStatusEqualTo(String value) {
            addCriterion("paper_status =", value, "paperStatus");
            return (Criteria) this;
        }

        public Criteria andPaperStatusNotEqualTo(String value) {
            addCriterion("paper_status <>", value, "paperStatus");
            return (Criteria) this;
        }

        public Criteria andPaperStatusGreaterThan(String value) {
            addCriterion("paper_status >", value, "paperStatus");
            return (Criteria) this;
        }

        public Criteria andPaperStatusGreaterThanOrEqualTo(String value) {
            addCriterion("paper_status >=", value, "paperStatus");
            return (Criteria) this;
        }

        public Criteria andPaperStatusLessThan(String value) {
            addCriterion("paper_status <", value, "paperStatus");
            return (Criteria) this;
        }

        public Criteria andPaperStatusLessThanOrEqualTo(String value) {
            addCriterion("paper_status <=", value, "paperStatus");
            return (Criteria) this;
        }

        public Criteria andPaperStatusLike(String value) {
            addCriterion("paper_status like", value, "paperStatus");
            return (Criteria) this;
        }

        public Criteria andPaperStatusNotLike(String value) {
            addCriterion("paper_status not like", value, "paperStatus");
            return (Criteria) this;
        }

        public Criteria andPaperStatusIn(List<String> values) {
            addCriterion("paper_status in", values, "paperStatus");
            return (Criteria) this;
        }

        public Criteria andPaperStatusNotIn(List<String> values) {
            addCriterion("paper_status not in", values, "paperStatus");
            return (Criteria) this;
        }

        public Criteria andPaperStatusBetween(String value1, String value2) {
            addCriterion("paper_status between", value1, value2, "paperStatus");
            return (Criteria) this;
        }

        public Criteria andPaperStatusNotBetween(String value1, String value2) {
            addCriterion("paper_status not between", value1, value2, "paperStatus");
            return (Criteria) this;
        }

        public Criteria andPaperAuthorIsNull() {
            addCriterion("paper_author is null");
            return (Criteria) this;
        }

        public Criteria andPaperAuthorIsNotNull() {
            addCriterion("paper_author is not null");
            return (Criteria) this;
        }

        public Criteria andPaperAuthorEqualTo(String value) {
            addCriterion("paper_author =", value, "paperAuthor");
            return (Criteria) this;
        }

        public Criteria andPaperAuthorNotEqualTo(String value) {
            addCriterion("paper_author <>", value, "paperAuthor");
            return (Criteria) this;
        }

        public Criteria andPaperAuthorGreaterThan(String value) {
            addCriterion("paper_author >", value, "paperAuthor");
            return (Criteria) this;
        }

        public Criteria andPaperAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("paper_author >=", value, "paperAuthor");
            return (Criteria) this;
        }

        public Criteria andPaperAuthorLessThan(String value) {
            addCriterion("paper_author <", value, "paperAuthor");
            return (Criteria) this;
        }

        public Criteria andPaperAuthorLessThanOrEqualTo(String value) {
            addCriterion("paper_author <=", value, "paperAuthor");
            return (Criteria) this;
        }

        public Criteria andPaperAuthorLike(String value) {
            addCriterion("paper_author like", value, "paperAuthor");
            return (Criteria) this;
        }

        public Criteria andPaperAuthorNotLike(String value) {
            addCriterion("paper_author not like", value, "paperAuthor");
            return (Criteria) this;
        }

        public Criteria andPaperAuthorIn(List<String> values) {
            addCriterion("paper_author in", values, "paperAuthor");
            return (Criteria) this;
        }

        public Criteria andPaperAuthorNotIn(List<String> values) {
            addCriterion("paper_author not in", values, "paperAuthor");
            return (Criteria) this;
        }

        public Criteria andPaperAuthorBetween(String value1, String value2) {
            addCriterion("paper_author between", value1, value2, "paperAuthor");
            return (Criteria) this;
        }

        public Criteria andPaperAuthorNotBetween(String value1, String value2) {
            addCriterion("paper_author not between", value1, value2, "paperAuthor");
            return (Criteria) this;
        }

        public Criteria andPaperTitleIsNull() {
            addCriterion("paper_title is null");
            return (Criteria) this;
        }

        public Criteria andPaperTitleIsNotNull() {
            addCriterion("paper_title is not null");
            return (Criteria) this;
        }

        public Criteria andPaperTitleEqualTo(String value) {
            addCriterion("paper_title =", value, "paperTitle");
            return (Criteria) this;
        }

        public Criteria andPaperTitleNotEqualTo(String value) {
            addCriterion("paper_title <>", value, "paperTitle");
            return (Criteria) this;
        }

        public Criteria andPaperTitleGreaterThan(String value) {
            addCriterion("paper_title >", value, "paperTitle");
            return (Criteria) this;
        }

        public Criteria andPaperTitleGreaterThanOrEqualTo(String value) {
            addCriterion("paper_title >=", value, "paperTitle");
            return (Criteria) this;
        }

        public Criteria andPaperTitleLessThan(String value) {
            addCriterion("paper_title <", value, "paperTitle");
            return (Criteria) this;
        }

        public Criteria andPaperTitleLessThanOrEqualTo(String value) {
            addCriterion("paper_title <=", value, "paperTitle");
            return (Criteria) this;
        }

        public Criteria andPaperTitleLike(String value) {
            addCriterion("paper_title like", value, "paperTitle");
            return (Criteria) this;
        }

        public Criteria andPaperTitleNotLike(String value) {
            addCriterion("paper_title not like", value, "paperTitle");
            return (Criteria) this;
        }

        public Criteria andPaperTitleIn(List<String> values) {
            addCriterion("paper_title in", values, "paperTitle");
            return (Criteria) this;
        }

        public Criteria andPaperTitleNotIn(List<String> values) {
            addCriterion("paper_title not in", values, "paperTitle");
            return (Criteria) this;
        }

        public Criteria andPaperTitleBetween(String value1, String value2) {
            addCriterion("paper_title between", value1, value2, "paperTitle");
            return (Criteria) this;
        }

        public Criteria andPaperTitleNotBetween(String value1, String value2) {
            addCriterion("paper_title not between", value1, value2, "paperTitle");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam_paper
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}