package com.ruicai.teaching.entity;

public class ExamAnswer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_answer.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_answer.student_id
     *
     * @mbggenerated
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_answer.answer_score
     *
     * @mbggenerated
     */
    private Short answerScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_answer.id
     *
     * @return the value of exam_answer.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_answer.id
     *
     * @param id the value for exam_answer.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_answer.student_id
     *
     * @return the value of exam_answer.student_id
     *
     * @mbggenerated
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_answer.student_id
     *
     * @param studentId the value for exam_answer.student_id
     *
     * @mbggenerated
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_answer.answer_score
     *
     * @return the value of exam_answer.answer_score
     *
     * @mbggenerated
     */
    public Short getAnswerScore() {
        return answerScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_answer.answer_score
     *
     * @param answerScore the value for exam_answer.answer_score
     *
     * @mbggenerated
     */
    public void setAnswerScore(Short answerScore) {
        this.answerScore = answerScore;
    }
}