package com.ruicai.teaching.entity;

public class ExamQuestion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_question.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_question.question_subject
     *
     * @mbggenerated
     */
    private String questionSubject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_question.question_type
     *
     * @mbggenerated
     */
    private String questionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_question.question_score
     *
     * @mbggenerated
     */
    private Short questionScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_question.question_content
     *
     * @mbggenerated
     */
    private String questionContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_question.question_answer
     *
     * @mbggenerated
     */
    private String questionAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_question.question_selections
     *
     * @mbggenerated
     */
    private Integer questionSelections;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_question.id
     *
     * @return the value of exam_question.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_question.id
     *
     * @param id the value for exam_question.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_question.question_subject
     *
     * @return the value of exam_question.question_subject
     *
     * @mbggenerated
     */
    public String getQuestionSubject() {
        return questionSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_question.question_subject
     *
     * @param questionSubject the value for exam_question.question_subject
     *
     * @mbggenerated
     */
    public void setQuestionSubject(String questionSubject) {
        this.questionSubject = questionSubject == null ? null : questionSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_question.question_type
     *
     * @return the value of exam_question.question_type
     *
     * @mbggenerated
     */
    public String getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_question.question_type
     *
     * @param questionType the value for exam_question.question_type
     *
     * @mbggenerated
     */
    public void setQuestionType(String questionType) {
        this.questionType = questionType == null ? null : questionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_question.question_score
     *
     * @return the value of exam_question.question_score
     *
     * @mbggenerated
     */
    public Short getQuestionScore() {
        return questionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_question.question_score
     *
     * @param questionScore the value for exam_question.question_score
     *
     * @mbggenerated
     */
    public void setQuestionScore(Short questionScore) {
        this.questionScore = questionScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_question.question_content
     *
     * @return the value of exam_question.question_content
     *
     * @mbggenerated
     */
    public String getQuestionContent() {
        return questionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_question.question_content
     *
     * @param questionContent the value for exam_question.question_content
     *
     * @mbggenerated
     */
    public void setQuestionContent(String questionContent) {
        this.questionContent = questionContent == null ? null : questionContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_question.question_answer
     *
     * @return the value of exam_question.question_answer
     *
     * @mbggenerated
     */
    public String getQuestionAnswer() {
        return questionAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_question.question_answer
     *
     * @param questionAnswer the value for exam_question.question_answer
     *
     * @mbggenerated
     */
    public void setQuestionAnswer(String questionAnswer) {
        this.questionAnswer = questionAnswer == null ? null : questionAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_question.question_selections
     *
     * @return the value of exam_question.question_selections
     *
     * @mbggenerated
     */
    public Integer getQuestionSelections() {
        return questionSelections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_question.question_selections
     *
     * @param questionSelections the value for exam_question.question_selections
     *
     * @mbggenerated
     */
    public void setQuestionSelections(Integer questionSelections) {
        this.questionSelections = questionSelections;
    }
}