package com.ruicai.teaching.entity;

import java.util.ArrayList;
import java.util.List;

public class ExamAnswerDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam_answer_detail
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam_answer_detail
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table exam_answer_detail
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer_detail
     *
     * @mbggenerated
     */
    public ExamAnswerDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer_detail
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer_detail
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer_detail
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer_detail
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer_detail
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer_detail
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer_detail
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer_detail
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer_detail
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer_detail
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam_answer_detail
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIsNull() {
            addCriterion("answer_id is null");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIsNotNull() {
            addCriterion("answer_id is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerIdEqualTo(String value) {
            addCriterion("answer_id =", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotEqualTo(String value) {
            addCriterion("answer_id <>", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdGreaterThan(String value) {
            addCriterion("answer_id >", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdGreaterThanOrEqualTo(String value) {
            addCriterion("answer_id >=", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdLessThan(String value) {
            addCriterion("answer_id <", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdLessThanOrEqualTo(String value) {
            addCriterion("answer_id <=", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdLike(String value) {
            addCriterion("answer_id like", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotLike(String value) {
            addCriterion("answer_id not like", value, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdIn(List<String> values) {
            addCriterion("answer_id in", values, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotIn(List<String> values) {
            addCriterion("answer_id not in", values, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdBetween(String value1, String value2) {
            addCriterion("answer_id between", value1, value2, "answerId");
            return (Criteria) this;
        }

        public Criteria andAnswerIdNotBetween(String value1, String value2) {
            addCriterion("answer_id not between", value1, value2, "answerId");
            return (Criteria) this;
        }

        public Criteria andPaperDetailIdIsNull() {
            addCriterion("paper_detail_id is null");
            return (Criteria) this;
        }

        public Criteria andPaperDetailIdIsNotNull() {
            addCriterion("paper_detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andPaperDetailIdEqualTo(String value) {
            addCriterion("paper_detail_id =", value, "paperDetailId");
            return (Criteria) this;
        }

        public Criteria andPaperDetailIdNotEqualTo(String value) {
            addCriterion("paper_detail_id <>", value, "paperDetailId");
            return (Criteria) this;
        }

        public Criteria andPaperDetailIdGreaterThan(String value) {
            addCriterion("paper_detail_id >", value, "paperDetailId");
            return (Criteria) this;
        }

        public Criteria andPaperDetailIdGreaterThanOrEqualTo(String value) {
            addCriterion("paper_detail_id >=", value, "paperDetailId");
            return (Criteria) this;
        }

        public Criteria andPaperDetailIdLessThan(String value) {
            addCriterion("paper_detail_id <", value, "paperDetailId");
            return (Criteria) this;
        }

        public Criteria andPaperDetailIdLessThanOrEqualTo(String value) {
            addCriterion("paper_detail_id <=", value, "paperDetailId");
            return (Criteria) this;
        }

        public Criteria andPaperDetailIdLike(String value) {
            addCriterion("paper_detail_id like", value, "paperDetailId");
            return (Criteria) this;
        }

        public Criteria andPaperDetailIdNotLike(String value) {
            addCriterion("paper_detail_id not like", value, "paperDetailId");
            return (Criteria) this;
        }

        public Criteria andPaperDetailIdIn(List<String> values) {
            addCriterion("paper_detail_id in", values, "paperDetailId");
            return (Criteria) this;
        }

        public Criteria andPaperDetailIdNotIn(List<String> values) {
            addCriterion("paper_detail_id not in", values, "paperDetailId");
            return (Criteria) this;
        }

        public Criteria andPaperDetailIdBetween(String value1, String value2) {
            addCriterion("paper_detail_id between", value1, value2, "paperDetailId");
            return (Criteria) this;
        }

        public Criteria andPaperDetailIdNotBetween(String value1, String value2) {
            addCriterion("paper_detail_id not between", value1, value2, "paperDetailId");
            return (Criteria) this;
        }

        public Criteria andAnswerContentIsNull() {
            addCriterion("answer_content is null");
            return (Criteria) this;
        }

        public Criteria andAnswerContentIsNotNull() {
            addCriterion("answer_content is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerContentEqualTo(String value) {
            addCriterion("answer_content =", value, "answerContent");
            return (Criteria) this;
        }

        public Criteria andAnswerContentNotEqualTo(String value) {
            addCriterion("answer_content <>", value, "answerContent");
            return (Criteria) this;
        }

        public Criteria andAnswerContentGreaterThan(String value) {
            addCriterion("answer_content >", value, "answerContent");
            return (Criteria) this;
        }

        public Criteria andAnswerContentGreaterThanOrEqualTo(String value) {
            addCriterion("answer_content >=", value, "answerContent");
            return (Criteria) this;
        }

        public Criteria andAnswerContentLessThan(String value) {
            addCriterion("answer_content <", value, "answerContent");
            return (Criteria) this;
        }

        public Criteria andAnswerContentLessThanOrEqualTo(String value) {
            addCriterion("answer_content <=", value, "answerContent");
            return (Criteria) this;
        }

        public Criteria andAnswerContentLike(String value) {
            addCriterion("answer_content like", value, "answerContent");
            return (Criteria) this;
        }

        public Criteria andAnswerContentNotLike(String value) {
            addCriterion("answer_content not like", value, "answerContent");
            return (Criteria) this;
        }

        public Criteria andAnswerContentIn(List<String> values) {
            addCriterion("answer_content in", values, "answerContent");
            return (Criteria) this;
        }

        public Criteria andAnswerContentNotIn(List<String> values) {
            addCriterion("answer_content not in", values, "answerContent");
            return (Criteria) this;
        }

        public Criteria andAnswerContentBetween(String value1, String value2) {
            addCriterion("answer_content between", value1, value2, "answerContent");
            return (Criteria) this;
        }

        public Criteria andAnswerContentNotBetween(String value1, String value2) {
            addCriterion("answer_content not between", value1, value2, "answerContent");
            return (Criteria) this;
        }

        public Criteria andAnswerDetailScoreIsNull() {
            addCriterion("answer_detail_score is null");
            return (Criteria) this;
        }

        public Criteria andAnswerDetailScoreIsNotNull() {
            addCriterion("answer_detail_score is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerDetailScoreEqualTo(Short value) {
            addCriterion("answer_detail_score =", value, "answerDetailScore");
            return (Criteria) this;
        }

        public Criteria andAnswerDetailScoreNotEqualTo(Short value) {
            addCriterion("answer_detail_score <>", value, "answerDetailScore");
            return (Criteria) this;
        }

        public Criteria andAnswerDetailScoreGreaterThan(Short value) {
            addCriterion("answer_detail_score >", value, "answerDetailScore");
            return (Criteria) this;
        }

        public Criteria andAnswerDetailScoreGreaterThanOrEqualTo(Short value) {
            addCriterion("answer_detail_score >=", value, "answerDetailScore");
            return (Criteria) this;
        }

        public Criteria andAnswerDetailScoreLessThan(Short value) {
            addCriterion("answer_detail_score <", value, "answerDetailScore");
            return (Criteria) this;
        }

        public Criteria andAnswerDetailScoreLessThanOrEqualTo(Short value) {
            addCriterion("answer_detail_score <=", value, "answerDetailScore");
            return (Criteria) this;
        }

        public Criteria andAnswerDetailScoreIn(List<Short> values) {
            addCriterion("answer_detail_score in", values, "answerDetailScore");
            return (Criteria) this;
        }

        public Criteria andAnswerDetailScoreNotIn(List<Short> values) {
            addCriterion("answer_detail_score not in", values, "answerDetailScore");
            return (Criteria) this;
        }

        public Criteria andAnswerDetailScoreBetween(Short value1, Short value2) {
            addCriterion("answer_detail_score between", value1, value2, "answerDetailScore");
            return (Criteria) this;
        }

        public Criteria andAnswerDetailScoreNotBetween(Short value1, Short value2) {
            addCriterion("answer_detail_score not between", value1, value2, "answerDetailScore");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam_answer_detail
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table exam_answer_detail
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}