package com.ruicai.teaching.entity;

public class ExamAnswerDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_answer_detail.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_answer_detail.answer_id
     *
     * @mbggenerated
     */
    private String answerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_answer_detail.paper_detail_id
     *
     * @mbggenerated
     */
    private String paperDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_answer_detail.answer_content
     *
     * @mbggenerated
     */
    private String answerContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_answer_detail.answer_detail_score
     *
     * @mbggenerated
     */
    private Short answerDetailScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_answer_detail.id
     *
     * @return the value of exam_answer_detail.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_answer_detail.id
     *
     * @param id the value for exam_answer_detail.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_answer_detail.answer_id
     *
     * @return the value of exam_answer_detail.answer_id
     *
     * @mbggenerated
     */
    public String getAnswerId() {
        return answerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_answer_detail.answer_id
     *
     * @param answerId the value for exam_answer_detail.answer_id
     *
     * @mbggenerated
     */
    public void setAnswerId(String answerId) {
        this.answerId = answerId == null ? null : answerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_answer_detail.paper_detail_id
     *
     * @return the value of exam_answer_detail.paper_detail_id
     *
     * @mbggenerated
     */
    public String getPaperDetailId() {
        return paperDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_answer_detail.paper_detail_id
     *
     * @param paperDetailId the value for exam_answer_detail.paper_detail_id
     *
     * @mbggenerated
     */
    public void setPaperDetailId(String paperDetailId) {
        this.paperDetailId = paperDetailId == null ? null : paperDetailId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_answer_detail.answer_content
     *
     * @return the value of exam_answer_detail.answer_content
     *
     * @mbggenerated
     */
    public String getAnswerContent() {
        return answerContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_answer_detail.answer_content
     *
     * @param answerContent the value for exam_answer_detail.answer_content
     *
     * @mbggenerated
     */
    public void setAnswerContent(String answerContent) {
        this.answerContent = answerContent == null ? null : answerContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_answer_detail.answer_detail_score
     *
     * @return the value of exam_answer_detail.answer_detail_score
     *
     * @mbggenerated
     */
    public Short getAnswerDetailScore() {
        return answerDetailScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_answer_detail.answer_detail_score
     *
     * @param answerDetailScore the value for exam_answer_detail.answer_detail_score
     *
     * @mbggenerated
     */
    public void setAnswerDetailScore(Short answerDetailScore) {
        this.answerDetailScore = answerDetailScore;
    }
}