package com.ruicai.teaching.entity;

import java.util.Date;

public class ExamArrangement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_arrangement.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_arrangement.class_id
     *
     * @mbggenerated
     */
    private String classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_arrangement.teacher_id
     *
     * @mbggenerated
     */
    private String teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_arrangement.paper_id
     *
     * @mbggenerated
     */
    private String paperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_arrangement.exam_stage
     *
     * @mbggenerated
     */
    private String examStage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_arrangement.exam_time
     *
     * @mbggenerated
     */
    private Date examTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exam_arrangement.exam_address
     *
     * @mbggenerated
     */
    private String examAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_arrangement.id
     *
     * @return the value of exam_arrangement.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_arrangement.id
     *
     * @param id the value for exam_arrangement.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_arrangement.class_id
     *
     * @return the value of exam_arrangement.class_id
     *
     * @mbggenerated
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_arrangement.class_id
     *
     * @param classId the value for exam_arrangement.class_id
     *
     * @mbggenerated
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_arrangement.teacher_id
     *
     * @return the value of exam_arrangement.teacher_id
     *
     * @mbggenerated
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_arrangement.teacher_id
     *
     * @param teacherId the value for exam_arrangement.teacher_id
     *
     * @mbggenerated
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId == null ? null : teacherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_arrangement.paper_id
     *
     * @return the value of exam_arrangement.paper_id
     *
     * @mbggenerated
     */
    public String getPaperId() {
        return paperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_arrangement.paper_id
     *
     * @param paperId the value for exam_arrangement.paper_id
     *
     * @mbggenerated
     */
    public void setPaperId(String paperId) {
        this.paperId = paperId == null ? null : paperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_arrangement.exam_stage
     *
     * @return the value of exam_arrangement.exam_stage
     *
     * @mbggenerated
     */
    public String getExamStage() {
        return examStage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_arrangement.exam_stage
     *
     * @param examStage the value for exam_arrangement.exam_stage
     *
     * @mbggenerated
     */
    public void setExamStage(String examStage) {
        this.examStage = examStage == null ? null : examStage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_arrangement.exam_time
     *
     * @return the value of exam_arrangement.exam_time
     *
     * @mbggenerated
     */
    public Date getExamTime() {
        return examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_arrangement.exam_time
     *
     * @param examTime the value for exam_arrangement.exam_time
     *
     * @mbggenerated
     */
    public void setExamTime(Date examTime) {
        this.examTime = examTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exam_arrangement.exam_address
     *
     * @return the value of exam_arrangement.exam_address
     *
     * @mbggenerated
     */
    public String getExamAddress() {
        return examAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exam_arrangement.exam_address
     *
     * @param examAddress the value for exam_arrangement.exam_address
     *
     * @mbggenerated
     */
    public void setExamAddress(String examAddress) {
        this.examAddress = examAddress == null ? null : examAddress.trim();
    }
}