package com.ruicai.teaching.dao;

import com.ruicai.teaching.entity.EduAttendance;
import com.ruicai.teaching.entity.EduAttendanceExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EduAttendanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    int countByExample(EduAttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    int deleteByExample(EduAttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    int insert(EduAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    int insertSelective(EduAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    List<EduAttendance> selectByExample(EduAttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    EduAttendance selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EduAttendance record, @Param("example") EduAttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EduAttendance record, @Param("example") EduAttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EduAttendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_attendance
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EduAttendance record);
}