package com.ruicai.teaching.dao;

import com.ruicai.teaching.entity.EduClass;
import com.ruicai.teaching.entity.EduClassExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EduClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_class
     *
     * @mbggenerated
     */
    int countByExample(EduClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_class
     *
     * @mbggenerated
     */
    int deleteByExample(EduClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_class
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_class
     *
     * @mbggenerated
     */
    int insert(EduClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_class
     *
     * @mbggenerated
     */
    int insertSelective(EduClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_class
     *
     * @mbggenerated
     */
    List<EduClass> selectByExample(EduClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_class
     *
     * @mbggenerated
     */
    EduClass selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_class
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EduClass record, @Param("example") EduClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_class
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EduClass record, @Param("example") EduClassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_class
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EduClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_class
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EduClass record);
}