package com.ruicai.teaching.dao;

import com.ruicai.teaching.entity.EduWork;
import com.ruicai.teaching.entity.EduWorkExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EduWorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    int countByExample(EduWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    int deleteByExample(EduWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    int insert(EduWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    int insertSelective(EduWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    List<EduWork> selectByExample(EduWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    EduWork selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EduWork record, @Param("example") EduWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EduWork record, @Param("example") EduWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EduWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table edu_work
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EduWork record);
}