package com.ruicai.teaching.dao;

import com.ruicai.teaching.entity.EvaEvaluationDetail;
import com.ruicai.teaching.entity.EvaEvaluationDetailExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EvaEvaluationDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation_detail
     *
     * @mbggenerated
     */
    int countByExample(EvaEvaluationDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation_detail
     *
     * @mbggenerated
     */
    int deleteByExample(EvaEvaluationDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation_detail
     *
     * @mbggenerated
     */
    int insert(EvaEvaluationDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation_detail
     *
     * @mbggenerated
     */
    int insertSelective(EvaEvaluationDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation_detail
     *
     * @mbggenerated
     */
    List<EvaEvaluationDetail> selectByExample(EvaEvaluationDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation_detail
     *
     * @mbggenerated
     */
    EvaEvaluationDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EvaEvaluationDetail record, @Param("example") EvaEvaluationDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EvaEvaluationDetail record, @Param("example") EvaEvaluationDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EvaEvaluationDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EvaEvaluationDetail record);
}