package com.ruicai.teaching.dao;

import com.ruicai.teaching.entity.EvaEvaluation;
import com.ruicai.teaching.entity.EvaEvaluationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EvaEvaluationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation
     *
     * @mbggenerated
     */
    int countByExample(EvaEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation
     *
     * @mbggenerated
     */
    int deleteByExample(EvaEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation
     *
     * @mbggenerated
     */
    int insert(EvaEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation
     *
     * @mbggenerated
     */
    int insertSelective(EvaEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation
     *
     * @mbggenerated
     */
    List<EvaEvaluation> selectByExample(EvaEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation
     *
     * @mbggenerated
     */
    EvaEvaluation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EvaEvaluation record, @Param("example") EvaEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EvaEvaluation record, @Param("example") EvaEvaluationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EvaEvaluation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_evaluation
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EvaEvaluation record);
}