package com.ruicai.teaching.dao;

import com.ruicai.teaching.entity.EvaMessage;
import com.ruicai.teaching.entity.EvaMessageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EvaMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_message
     *
     * @mbggenerated
     */
    int countByExample(EvaMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_message
     *
     * @mbggenerated
     */
    int deleteByExample(EvaMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_message
     *
     * @mbggenerated
     */
    int insert(EvaMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_message
     *
     * @mbggenerated
     */
    int insertSelective(EvaMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_message
     *
     * @mbggenerated
     */
    List<EvaMessage> selectByExample(EvaMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_message
     *
     * @mbggenerated
     */
    EvaMessage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_message
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") EvaMessage record, @Param("example") EvaMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_message
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") EvaMessage record, @Param("example") EvaMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EvaMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eva_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EvaMessage record);
}