package com.ruicai.teaching.dao;

import com.ruicai.teaching.entity.ExamArrangement;
import com.ruicai.teaching.entity.ExamArrangementExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ExamArrangementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_arrangement
     *
     * @mbggenerated
     */
    int countByExample(ExamArrangementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_arrangement
     *
     * @mbggenerated
     */
    int deleteByExample(ExamArrangementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_arrangement
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_arrangement
     *
     * @mbggenerated
     */
    int insert(ExamArrangement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_arrangement
     *
     * @mbggenerated
     */
    int insertSelective(ExamArrangement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_arrangement
     *
     * @mbggenerated
     */
    List<ExamArrangement> selectByExample(ExamArrangementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_arrangement
     *
     * @mbggenerated
     */
    ExamArrangement selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_arrangement
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ExamArrangement record, @Param("example") ExamArrangementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_arrangement
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ExamArrangement record, @Param("example") ExamArrangementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_arrangement
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExamArrangement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_arrangement
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExamArrangement record);
}