package com.ruicai.teaching.dao;

import com.ruicai.teaching.entity.ExamAnswer;
import com.ruicai.teaching.entity.ExamAnswerExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ExamAnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer
     *
     * @mbggenerated
     */
    int countByExample(ExamAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer
     *
     * @mbggenerated
     */
    int deleteByExample(ExamAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer
     *
     * @mbggenerated
     */
    int insert(ExamAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer
     *
     * @mbggenerated
     */
    int insertSelective(ExamAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer
     *
     * @mbggenerated
     */
    List<ExamAnswer> selectByExample(ExamAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer
     *
     * @mbggenerated
     */
    ExamAnswer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ExamAnswer record, @Param("example") ExamAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ExamAnswer record, @Param("example") ExamAnswerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExamAnswer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_answer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExamAnswer record);
}