package com.ruicai.teaching.dao;

import com.ruicai.teaching.entity.ExamPaper;
import com.ruicai.teaching.entity.ExamPaperExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ExamPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int countByExample(ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int deleteByExample(ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int insert(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int insertSelective(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    List<ExamPaper> selectByExample(ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    ExamPaper selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ExamPaper record, @Param("example") ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ExamPaper record, @Param("example") ExamPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExamPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExamPaper record);
}