package com.ruicai.teaching.dao;

import com.ruicai.teaching.entity.ExamPaperDetail;
import com.ruicai.teaching.entity.ExamPaperDetailExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ExamPaperDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper_detail
     *
     * @mbggenerated
     */
    int countByExample(ExamPaperDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper_detail
     *
     * @mbggenerated
     */
    int deleteByExample(ExamPaperDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper_detail
     *
     * @mbggenerated
     */
    int insert(ExamPaperDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper_detail
     *
     * @mbggenerated
     */
    int insertSelective(ExamPaperDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper_detail
     *
     * @mbggenerated
     */
    List<ExamPaperDetail> selectByExample(ExamPaperDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper_detail
     *
     * @mbggenerated
     */
    ExamPaperDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ExamPaperDetail record, @Param("example") ExamPaperDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ExamPaperDetail record, @Param("example") ExamPaperDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ExamPaperDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exam_paper_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ExamPaperDetail record);
}