package com.ruicai.teaching.dao;

import com.ruicai.teaching.entity.SysRole2resExample;
import com.ruicai.teaching.entity.SysRole2resKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysRole2resMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2res
     *
     * @mbggenerated
     */
    int countByExample(SysRole2resExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2res
     *
     * @mbggenerated
     */
    int deleteByExample(SysRole2resExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2res
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SysRole2resKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2res
     *
     * @mbggenerated
     */
    int insert(SysRole2resKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2res
     *
     * @mbggenerated
     */
    int insertSelective(SysRole2resKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2res
     *
     * @mbggenerated
     */
    List<SysRole2resKey> selectByExample(SysRole2resExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2res
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysRole2resKey record, @Param("example") SysRole2resExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role2res
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysRole2resKey record, @Param("example") SysRole2resExample example);
}