package com.ruicai.teaching.dao;

import com.ruicai.teaching.entity.SysRes;
import com.ruicai.teaching.entity.SysResExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysResMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res
     *
     * @mbggenerated
     */
    int countByExample(SysResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res
     *
     * @mbggenerated
     */
    int deleteByExample(SysResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res
     *
     * @mbggenerated
     */
    int insert(SysRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res
     *
     * @mbggenerated
     */
    int insertSelective(SysRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res
     *
     * @mbggenerated
     */
    List<SysRes> selectByExample(SysResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res
     *
     * @mbggenerated
     */
    SysRes selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysRes record, @Param("example") SysResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysRes record, @Param("example") SysResExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_res
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRes record);
}