package com.ruicai.teaching.dao;

import com.ruicai.teaching.entity.SysUser2roleExample;
import com.ruicai.teaching.entity.SysUser2roleKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysUser2roleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbggenerated
     */
    int countByExample(SysUser2roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbggenerated
     */
    int deleteByExample(SysUser2roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(SysUser2roleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbggenerated
     */
    int insert(SysUser2roleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbggenerated
     */
    int insertSelective(SysUser2roleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbggenerated
     */
    List<SysUser2roleKey> selectByExample(SysUser2roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysUser2roleKey record, @Param("example") SysUser2roleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysUser2roleKey record, @Param("example") SysUser2roleExample example);
}